version: '3.7'
services:
#mongo db database
  mongodb_container:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
     - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

#mongo db Viwer
  mongo_express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb_container:27017/

#MySql Db
  mysql:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '3306:3306'
      expose:
        - '3306'
      volumes:
        - mysql-volume:/var/lib/mysql
        - mycustom.cnf:/etc/mysql/conf.d/custom.cnf
      command: mysqld --character-set-server=utf8 --collation-server=utf8_turkish_ci
  

volumes:
  mongodb:
  mongodb_config:
  mysql-volume:
  mycustom.cnf: